#!/usr/bin/env python3
# coding: utf-8

import os
import skjult

from docopt import docopt
from skjult.cli import Cli

doc = """Skjult, encfs containers manager.

Usage:
  skjult (create|mount|umount|delete) <name>
  skjult list
  skjult -h | --help
  skjult -v | --version

Options:
  -h --help           Show help
  -v --version        Show version

Importants:
  You need encfs package
  You need to be in sudoers file
  You need to modprobe fuse
  You need to be in fuse group
"""

if __name__ == '__main__':
	args = docopt(doc, version=skjult.__version__)
	cli = Cli(**args)
	cli.start()
